-- nyanuwatari — shipwright build orchestrator.
-- Run via:  just extras

local M = {}

local AUTOGEN_HEADER = {
  "# nyanuwatari — coding colorscheme by Marek Honzal",
  "# https://github.com/marekh19/nyanuwatari.nvim",
  "# Auto-generated by shipwright. Do not edit by hand.",
}

function M.run()
  local run = require("shipwright.builder").run
  local prepend = require("shipwright.transform.prepend")
  local overwrite = require("shipwright.transform.overwrite")

  local kitty = require("shipwright.transform.contrib.kitty")
  local alacritty = require("shipwright.transform.contrib.alacritty")
  local wezterm = require("shipwright.transform.contrib.wezterm")
  local ghostty = require("nyanuwatari.shipwright.runners.ghostty")
  local tmux = require("nyanuwatari.shipwright.runners.tmux")

  local palette = require("nyanuwatari.palette").dark
  local colors = require("nyanuwatari.term").colors_map(palette)

  -- Add metadata that the kitty contrib transform can render.
  local kitty_colors = vim.tbl_extend("force", colors, {
    name = "Nyanuwatari",
    author = "Marek Honzal",
    license = "MIT",
    upstream = "https://github.com/marekh19/nyanuwatari.nvim",
    blurb = "A charcoal coding colorscheme.",
  })

  -- Kitty
  run(
    kitty_colors,
    kitty,
    { prepend, AUTOGEN_HEADER },
    { overwrite, "extras/kitty/nyanuwatari.conf" }
  )

  -- Alacritty (shipwright emits the legacy YAML format)
  run(
    colors,
    alacritty,
    { prepend, AUTOGEN_HEADER },
    { overwrite, "extras/alacritty/nyanuwatari.yml" }
  )

  -- WezTerm (drop into ~/.config/wezterm/colors/)
  run(
    colors,
    wezterm,
    { prepend, AUTOGEN_HEADER },
    { overwrite, "extras/wezterm/nyanuwatari.toml" }
  )

  -- Ghostty
  run(colors, ghostty, { prepend, AUTOGEN_HEADER }, { overwrite, "extras/ghostty/nyanuwatari" })

  -- Tmux
  run(colors, tmux, { prepend, AUTOGEN_HEADER }, { overwrite, "extras/tmux/nyanuwatari.tmux" })

  print("nyanuwatari: regenerated extras/ ✓")
end

return M
